### ISSUE TITLE
Add URAP for Fall 2023 to Opportunities page

### ISSUE THREAD

**Issue by thomason-jesse** [GLAMOR-USC/glamor-usc.github.io#10]
**Opportunity:** USC Undergraduate Research Associates Program

**Time:** Fall 2023-Spring 2024 semesters for 8-10 hours per week

**Compensation:** $1500/semester ($3000 total)

**How to apply:** Fill the interest form linked above.

**Eligibility:** 
Undergraduate rising sophomore/junior/senior who does not hit any ineligibility criteria below.
Undergraduate students are **ineligible** for URAP funding if they:
- Enroll in a Progressive Degree Program (PDP)
- Enroll in a 490 (directed research class)
- Officially graduated from USC
- Take a leave of absence.
- Enroll in less than 12 units at the time when you make payment request.
- Receive either a Provost, CURVE, SOAR, or SURF funding (students cannot receive two sources of funding in the same term).

**Prerequisites skills:**
- Algorithms: CSCI 270; Linear Algebra: MATH 225; Probability: EE 364 or MATH 407 or BUAD 310
- Familiarity with Python and associated ML frameworks such as NumPy, Pandas, and Pytorch
- Willingness to work across multiple subfields of AI (e.g., language, vision, robotics) and read papers from out-of-discipline 
- Bonus: CSCI 467 or other machine learning course (e.g., CSCI 499's that involve ML or NLP), possibly concurrently with project

**Skills you will acquire:**
- Training and evaluating deep learning models in Pytorch
- Wrangling large scale data from multiple sources
- Designing experiments for human subjects
- Graphics and animation and/or basic robotics controls

**Project Brief Description:**

Human cognition is situated in the physical bodies and spaces people occupy, yet automated instruction (e.g., recorded videos of classes or tutorials) is typically communicated verbally to stationary learners. This work will leverage embodied tutors, from virtual avatars to physical robots, to engage learners via combinations of verbal and gestural cues, and in turn study how learner gesture repetition can serve to improve information recall. Specifically, this work will test the hypothesis that learners who _see_ a tutor perform iconic gestures representing new words that they _hear_ from the tutor will be better able to recall those words than learners who do not see such gestures and than learners who do not repeat both the verbal and gestural inputs to the tutor.

Experiments will be conducted in the context of second language (L2) acquisition, where an ongoing subtask is _lexical acquisition_: memorizing content words in the target language. Prior work has shown that, in the context of second language (L2) learning, both listening comprehension and word retention are improved when instruction is accompanied by tutor gestures. This work will evaluate the hypothesis that combining iconic and metaphoric gesture production during both speaking and hearing of information those gestures represent will improve retention of new information for learners, and that this effect will be stronger with a robot tutor than with recordings or avatars.

**Comment by tejas1995** [comment]
Let me know if this is ok or if it's ugly and I should make a drop down kinda thing with details instead
