### ISSUE TITLE
update opportunities page with CURVE 2023-4 info

### ISSUE THREAD

**Issue by thomason-jesse** [GLAMOR-USC/glamor-usc.github.io#14]
Probably just giving instructions about how to get to the lab's project lists + a bulleted list of who is eligible is fine. No need to repost all the projects' info

https://viterbiundergrad.usc.edu/research/curve/research-positions/

**Comment by tejas1995** [comment]
should I leave URAP up still?

**Comment by thomason-jesse** [comment]
Yeah

**Comment by tejas1995** [comment]
Done, lmk if it looks ok.
