### ISSUE TITLE
[People] Move Junu to "Previous Visiting Students"

### ISSUE THREAD

**Issue by thomason-jesse** [GLAMOR-USC/glamor-usc.github.io#2]

**Comment by tejas1995** [comment]
I've done that, but maybe we want to differentiate between Visiting Students and Undergrads? I think a clickable Previous Students for the Undergrads section that expands when selected would be better.

**Comment by thomason-jesse** [comment]
You could make an "Alumni" section at the bottom that's binned into phd/ms/ugrad/visiting and just has names / brief description / deliverable  without any picture, just a bulleted list. I see that on other lab sites

**Comment by tejas1995** [comment]
Bulleted list sounds good, yeah. Do Previous Visiting Students go into Alumni? I think the ones who aren't part of the lab anymore (like last summer visitors) can go into the Alumni section, and we don't need a separate section for Previous Visiting Students (i.e. what we have now). And if we have any "Current Visitors" we can add them while they're actually part of the lab.

**Comment by thomason-jesse** [comment]
Sounds good
