### ISSUE TITLE
Add LAS to sponsors page

### ISSUE THREAD

**Issue by thomason-jesse** [GLAMOR-USC/glamor-usc.github.io#4]
Continual Learning of Few-shot Learners for Natural Language Processing

Sponsor: Laboratory for Analytic Sciences (LAS); https://ncsu-las.org/

People: Mohammad Rostami (PI) https://rostami-m.github.io/, Jesse Thomason (co-PI)

Grant Duration: May 2022 - April 2023

---

If you want to set up a Project Page similar to what Maja's interaction lab does, we could add products so far like the NeurIPS paper and also list current and previous collaborators among PhD and ugrad students.

**Comment by tejas1995** [comment]
Is there a Grant ID for LAS?

Maja's lab seems to make a complete webpage for each project - I don't know if our lab folks would be interested in doing that for each project (even just the funded ones). I can list Current and Past Collaborators (is this where PhD students go? maybe rename the "People" row to "Principal Investigators"?) for each project, and Publications (I think just CLiMB so far?)

**Comment by thomason-jesse** [comment]
No, there isn't.

Up to you for now. If you think it's all small scale enough not to need anything more for a while the extra info sounds fine.

**Comment by tejas1995** [comment]
who are the students for the other grants? I'm including me Charlotte Leticia and Yuliang in the LAS one.

**Comment by tejas1995** [comment]
bump

**Comment by thomason-jesse** [comment]
A2I2: Ishika

CAA: Abrar

ADRD: Leticia, Leslie, Julie

LAS: Tejas, Yuliang, Anthony, Charlotte, Leticia, Flora + publication

**Comment by tejas1995** [comment]
what's CAA? is that the convergence accelerator?
